tap "homebrew/cask"

brew "rbenv"
brew "git"
brew "git-extras"
brew "the_silver_searcher"
brew "ripgrep"
brew "mitmproxy"
brew "jq"
brew "tree"
brew "shellcheck"
brew "starship"
brew "graphviz"
brew "mkcert"
brew "nss"
brew "colima"

tap "sqldef/sqldef"
brew "sqldef/sqldef/mysqldef"

tap "railwaycat/emacsmacport"
cask "emacs-mac"
cask "hammerspoon"

tap "homebrew/cask-fonts"
cask "font-fira-code-nerd-font"
cask "squirrel"
