brew "automake"
brew "rbenv"
brew "fnm"
brew "git"
brew "git-extras"
brew "the_silver_searcher"
brew "ripgrep"
brew "mitmproxy"
brew "jq"
brew "yq"
brew "tree"
brew "shellcheck"
brew "starship"
brew "graphviz"
brew "mkcert"
brew "nss"
brew "docker"
brew "docker-buildx"
brew "colima"
brew "zig"
brew "ctags"

tap "sqldef/sqldef"
brew "sqldef/sqldef/mysqldef"

tap "railwaycat/emacsmacport"
cask "emacs-mac"
cask "hammerspoon"
